apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}dbmigrator-config
type: Opaque
stringData:
  refinery.toml: |-
    [main]
    db_type = "Postgres"
    db_host = "{{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}"
    db_port = "{{ .Values.db.port }}"
    db_name = "{{ .Values.db.dbname }}"
    db_user = "{{ .Values.db.user }}"
    db_pass = "{{ .Values.db.password }}"
    trust_cert = false
